"use client";

import { useState } from "react";

export default function DeletionRequestForm({ empresaName, pending }: { empresaName: string; pending: boolean }) {
  const [open, setOpen] = useState(false); const [confirmation, setConfirmation] = useState(""); const [reason, setReason] = useState(""); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setMessage(""); try { const response = await fetch("/api/dados/exclusao", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ confirmation, reason }) }); const data = await response.json().catch(() => ({})); if (!response.ok) return setMessage(data.error ?? "Não foi possível enviar a solicitação."); setMessage("Solicitação enviada para análise. Nenhum dado foi apagado neste momento."); setOpen(false); } catch { setMessage("Erro de conexão. Tente novamente."); } finally { setLoading(false); } }
  if (pending) return <div className="card"><span className="pill pill-warn">Exclusão em análise</span><p className="text-sm mt-2" style={{ color: "var(--ink-soft)" }}>Nenhum dado será apagado antes da revisão administrativa.</p></div>;
  return <div className="card space-y-3"><div><h2 className="font-bold">Encerrar conta da empresa</h2><p className="text-sm" style={{ color: "var(--ink-soft)" }}>A solicitação passa por revisão antes de qualquer exclusão.</p></div>{!open ? <button className="btn-secondary" onClick={() => setOpen(true)}>Solicitar exclusão</button> : <form className="space-y-3" onSubmit={submit}><div><label className="label" htmlFor="delete-reason">Motivo (opcional)</label><textarea id="delete-reason" className="input" maxLength={1000} value={reason} onChange={(event) => setReason(event.target.value)} /></div><div><label className="label" htmlFor="delete-confirmation">Digite: {empresaName}</label><input id="delete-confirmation" className="input" required value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></div><div className="flex gap-2"><button className="btn-primary" disabled={loading || confirmation !== empresaName}>{loading ? "Enviando..." : "Enviar para análise"}</button><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>Cancelar</button></div></form>}{message && <p className="text-sm">{message}</p>}</div>;
}
